name: Unit Tests and Fuzzing Tests

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.0
        
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
      
    - name: Build bootstrap
      run: make bootstrap

    - name: Build upstream-protobom
      run: make upstream-protobom

    - name: Copy goreleaser.yaml
      run: cp .goreleaser.yaml ./.tmp/goreleaser.yaml
      
    - name: Build binary
      run: make binary

    - name: Run unit tests
      run: make unittest

    - name: Run fuzzing tests
      run: make fuzztest